config/routes.rb
Citizenry::Application.routes.draw do 
  root :to => "site#index"

  get '/search(/:query)' => 'site#search', :as => :search
  get '/s(/:query)' => 'site#search', :as => :short_search
  get '/opensearch(.:format)' => 'site#opensearch', :as => :opensearch

  resources :authentications
  resources :companies do
    member do
      post 'join'
      post 'leave'
    end
  end
  get '/companies/tag/:tag(.:format)' => 'companies#tag', :as => 'companies_tagged', :constraints => {:tag => /.*/}

  resources :groups do
    member do
      post 'join'
      post 'leave'
    end
  end
  get '/groups/tag/:tag(.:format)' => 'groups#tag', :as => 'groups_tagged', :constraints => {:tag=> /.*/}

  resources :people do
    collection do
      get 'grid', :action => :index, :grid => '1'
    end
    member do
      get 'claim'
      get 'photo'
    end
  end
  get '/people/tag/:tag(.:format)' => 'people#tag', :as => 'people_tagged', :constraints => {:tag => /.*/}

  resources :projects do
    member do
      post 'join'
      post 'leave'
    end
  end
  get '/projects/tag/:tag(.:format)' => 'projects#tag', :as => 'projects_tagged', :constraints => {:tag => /.*/}

  resources :resources, :as => :resource_links, :controller => :resource_links

  resources :users, :only => [:show, :index, :destroy] do
    member do
      post 'adminify'
    end
  end
  get '/welcome' => 'users#welcome', :as => 'welcome_users'
  get '/home' => 'users#home', :as => 'home_users'

  resources :user_sessions, :only => [:new, :create], :controller => 'users/sessions'

  devise_for :users do
    get "/sign_out" => "devise/sessions#destroy"
    get "/sign_in" => "users/sessions#new"
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/auto' => 'authentications#auto'
  match '/auth/failure' => 'authentications#auth_failure'

  resources :changes, :controller => 'paper_trail_manager/changes'

end

app/models/group.rb
class Group < ActiveRecord::Base
  include SearchEngine
  has_paper_trail :ignore => [:delta]
  acts_as_taggable_on :tags, :technologies
  sortable :created_at, :desc

  has_attached_file :logo, :styles => { :medium => '220x220', :thumb => '48x48' }, :url => "/system/:attachment/:id/:style/:safe_filename"

  default_serialization_options :include => { :projects => {:include => [:tags, :technologies]}, 
                                              :companies => {:include => [:tags, :technologies]},
                                              :members  => {:include => [:tags, :technologies]},
                                              :tags => {},
                                              :technologies => {}}

  has_many :group_projects
  has_many :projects, :through => :group_projects

  has_many :group_memberships
  has_many :members, :through => :group_memberships, :source => :person

  has_many :sponsorships
  has_many :companies, :through => :sponsorships

  validates_presence_of :name
end




# == Schema Information
#
# Table name: groups
#
#  id                :integer(4)      not null, primary key
#  name              :string(255)
#  description       :text
#  url               :string(255)
#  mailing_list      :string(255)
#  twitter           :string(255)
#  meeting_info      :text
#  created_at        :datetime
#  updated_at        :datetime
#  logo_url          :string(255)
#  logo_file_name    :string(255)
#  logo_content_type :string(255)
#  logo_file_size    :integer(4)
#  logo_updated_at   :datetime
#  delta             :boolean(1)      default(TRUE), not null
#

app/controllers/groups_controller.rb
class GroupsController < InheritedResources::Base
  respond_to :html, :xml, :json
  custom_actions  :collection => :tag,
                  :resource => [:join, :leave]

  before_filter :authenticate_user!, :except => [:index, :show, :tag]

  def tag
    @tag = params[:tag]

    tag! do |format|
      format.html { render :action => :index }
    end
  end

  def join
    resource.members << current_person if current_person
    join!{ {:action => :show} }
  end

  def leave
    resource.members.delete(current_person) if current_person
    leave!{ {:action => :show} }
  end

  protected

  def collection
    @groups ||= filter_sort_and_paginate(end_of_association_chain)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= semantic_form_for(@group, :html => {:multipart => true}) do |f|
  = f.inputs do
    = f.input :name :label => "Nom"
    = f.input :url, :label => 'Website'
    = f.input :mailing_list, :hint => "URL pour liste d'information"
    = f.input :description
    = f.input :meeting_info
    = f.input :tag_list, :as => :text, :label => 'Tags', :hint => "Séparés par des virgules, svp", :input_html => {:class => 'tags'}
    = f.input :technology_list, :as => :text, :label => 'Technologies (langages, frameworks, etc)', :hint => "Séparés par des virgules, svp", :input_html => {:class => 'tags'}
    - if @group.logo.file?
      %li
        .faux_label Current logo
        = image_tag @group.logo.url(:medium) if @group.logo.present?
    = f.input :logo, :label => "Uploader un logo", :hint => "De préférence de 220px de large ou plus"
  = f.buttons

app/views/groups/_list.html.haml
- context ||= :general
%ul{:class => 'resource_list groups'}
  = render :partial => 'groups/list_item', :collection => list, :locals => {:context => context}
= render :partial => 'shared/list_pagination', :object => list

app/views/groups/_list_item.html.haml
- context ||= :general
%li.group
  - if list_item.logo.file?
    = link_to image_tag(list_item.logo.url(:thumb)), group_path(list_item), :class => 'avatar'
  %h3
    =link_to list_item.name, group_path(list_item)
  - if list_item.twitter.present?
    %span{:class => 'twitter_link'}
      %a{:href => "https://twitter.com/#{list_item.twitter}"}= "@#{list_item.twitter}"
      sur Twitter
  -#%p{:class=>'location'}= person['location']
  %p{:class=>'description'}= truncate(strip_links(list_item.description), :length => 350)

app/views/groups/edit.html.erb
<h1>Edité le groupe</h1>

<%= render 'form' %>

<%= link_to 'Voir', @group %> |
<%= link_to 'Retour', groups_path %>

app/views/groups/index.html.haml
- content_for(:section_header) do
  .section_header{:class => 'groups'}
    %h1= semantic_pluralize(@groups.respond_to?(:total_entries) ? @groups.total_entries : @groups.size, "#{@tag} groupe".strip.titleize)
    = link_to "+ Ajouter un groupe", new_group_path, :class => 'new'
    #view_options
      %span.sorting
        %strong Trier par:
        = sort_link(:name, :label => "Nom") + ","
        = sort_link(:created_at, :label => "Date d'ajout", :default_order => :desc, :is_default => :desc) + ","
        = sort_link(:random, :label => "Aléatoire")

= render :partial => 'groups/list', :object => @groups

app/views/groups/new.html.erb
<h1>Nouveau group</h1>

<%= render 'form' %>

<%= link_to 'Retour', groups_path %>

app/views/groups/show.html.haml
.single_record.group{:class => @group.logo.file? ? 'with_image' : 'without_image'}
  = image_tag(@group.logo.url(:medium), :class => 'logo') if @group.logo.file?
  %h1= @group.name
  - if @group.description.present?
    .description= simple_format @group.description
  - if @group.meeting_info.present?
    %h2 Informations de rencontres
    .description= simple_format @group.meeting_info
  .links
    - if [@group.url, @group.mailing_list].any?{|link| link.present?}
      %h2 Liens
    - if @group.url.present?
      =link_to normalize_url(@group.url), normalize_url(@group.url), :class => 'url'
    - if @group.mailing_list.present?
      =link_to "Liste de discussion", normalize_url(@group.mailing_list), :class => 'mailing_list'

  .record_actions
    = link_to 'Editer', edit_group_path(@group), :class => 'edit'
    = link_to "Supprimer", group_path(@group), :confirm => 'Are you sure?', :method => :delete, :class => 'delete'

  - if @group.tags.present?
    .section.tags
      %h2 Tags
      = render :partial => 'tags/list', :object => @group.tags, :locals => {:type => :group}

  - if @group.technologies.present?
    .section.technologies
      %h2 Technologies
      = render :partial => 'tags/list', :object => @group.technologies, :locals => {:type => :group}

  .section.members
    %h2 Membres
    - if current_person
      - if @group.members.include?(current_person)
        = link_to "Quitter ce groupe", leave_group_path(@group), :class => 'leave', :method => :post
      - else
        = link_to "Joindre ce groupe", join_group_path(@group), :class => 'join', :method => :post
    = render :partial => 'people/list', :object => @group.members, :locals => {:context => :member_list}