config/routes.rb
Citizenry::Application.routes.draw do 
  root :to => "site#index"

  get '/search(/:query)' => 'site#search', :as => :search
  get '/s(/:query)' => 'site#search', :as => :short_search
  get '/opensearch(.:format)' => 'site#opensearch', :as => :opensearch

  resources :authentications
  resources :companies do
    member do
      post 'join'
      post 'leave'
    end
  end
  get '/companies/tag/:tag(.:format)' => 'companies#tag', :as => 'companies_tagged', :constraints => {:tag => /.*/}

  resources :groups do
    member do
      post 'join'
      post 'leave'
    end
  end
  get '/groups/tag/:tag(.:format)' => 'groups#tag', :as => 'groups_tagged', :constraints => {:tag=> /.*/}

  resources :people do
    collection do
      get 'grid', :action => :index, :grid => '1'
    end
    member do
      get 'claim'
      get 'photo'
    end
  end
  get '/people/tag/:tag(.:format)' => 'people#tag', :as => 'people_tagged', :constraints => {:tag => /.*/}

  resources :projects do
    member do
      post 'join'
      post 'leave'
    end
  end
  get '/projects/tag/:tag(.:format)' => 'projects#tag', :as => 'projects_tagged', :constraints => {:tag => /.*/}

  resources :resources, :as => :resource_links, :controller => :resource_links

  resources :users, :only => [:show, :index, :destroy] do
    member do
      post 'adminify'
    end
  end
  get '/welcome' => 'users#welcome', :as => 'welcome_users'
  get '/home' => 'users#home', :as => 'home_users'

  resources :user_sessions, :only => [:new, :create], :controller => 'users/sessions'

  devise_for :users do
    get "/sign_out" => "devise/sessions#destroy"
    get "/sign_in" => "users/sessions#new"
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/auto' => 'authentications#auto'
  match '/auth/failure' => 'authentications#auth_failure'

  resources :changes, :controller => 'paper_trail_manager/changes'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_protected :admin

  has_paper_trail :ignore => [:remember_token, :remember_created_at, :sign_in_count, :current_sign_in_at, :last_sign_in_ip, :last_sign_in_ip, :updated_at]

  has_one :person
  has_many :authentications, :dependent => :destroy do
    def info_get(key)
      info_with_key = self.map(&:info).compact.detect{|info| info[key].present? }
      return info_with_key[key] if info_with_key.present?
    end
  end

  devise :rememberable, :trackable

  def avatar_url
    if self.person.try(:photo_file_name).present?
      self.person.try(:photo).try(:url, :thumb) || self.authentications.info_get(:image)
    end
  end

  def name
    self.person.try(:name) || self.authentications.info_get(:name) || "User #{self.id}"
  end

  def label_for_admin
    "#{self.id}: #{self.name} #{self.person.present? ? '*' : ''}"
  end

  def default_authentication
    self.authentications.first
  end

  def has_auth_from?(provider)
    self.authentications.via(provider).present?
  end

  SAMPLE_USER = {
    :email => "sample@sample.org",
    :admin => true,
  }

  def self.find_sample
    return self.where(:email => User::SAMPLE_USER[:email]).first
  end

  def self.find_or_create_sample(create_backreference=true)
    user = self.find_sample
    unless user
      user = self.create!(SAMPLE_USER)
    end
    if create_backreference && ! user.person
      person = Person.find_or_create_sample(false)
      user.person = person
      user.save!
    end
    return user
  end
end






# == Schema Information
#
# Table name: users
#
#  id                  :integer(4)      not null, primary key
#  remember_token      :string(255)
#  remember_created_at :datetime
#  sign_in_count       :integer(4)      default(0)
#  current_sign_in_at  :datetime
#  last_sign_in_at     :datetime
#  current_sign_in_ip  :string(255)
#  last_sign_in_ip     :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  admin               :boolean(1)      default(FALSE)
#  email               :string(255)
#

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  def new
    @signin_data = SignInData.new
  end

  def create
    @signin_data = SignInData.new(params[:sign_in_data])
    render(:action => :new) and return unless @signin_data.valid?

    session[:login_email] = @signin_data.email

    if @signin_data.provider == 'auto'
      redirect_to :controller => '/authentications', :action => :auto, :email => @signin_data.email
    else
      redirect_to "/auth/#{@signin_data.provider}"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  respond_to :html, :xml, :json

  before_filter :authenticate_user!, :only => [:welcome, :home]
  before_filter :require_admin!, :except => [:show, :home, :welcome]

  def show
    if resource.person
      redirect_to person_path(resource.person)
    else
      if current_user && current_user.admin?
        redirect_to users_path(:anchor => "user_#{resource.id}")
      else
        raise ActiveRecord::RecordNotFound
      end
    end
  end

  def home
    redirect_to :action => :welcome and return unless current_user.person.try(:reviewed)
  end

  def welcome
    redirect_to :action => :home and return if current_user.person.try(:reviewed)

    @name = current_user.name || params[:name]
    @person = current_user.person || current_user.authentications.first.to_person || Person.new

    if @person.new_record?
      if @name.present?
        @possible_duplicates = Person.unclaimed.where(:name => @name).all

        name_parts = @name.split(' ')
        name_part_query = (["name LIKE ?"] * name_parts.size).join(' or ')
        @possible_duplicates += Person.unclaimed.where(name_part_query, *name_parts.map{|p| "%#{p}%"}).take(10)

        @possible_duplicates.uniq!
      end
    end
  end

  def index
    @users = User.includes(:authentications, :person).all
  end

  # def destroy

  def adminify
    @user.admin = !(@user.admin)
    @user.save

    redirect_to users_path
  end
end

app/views/users/home.html.haml
- content_for(:section_header) do
  .section_header{:class => 'events'}
    %h1 Hey là bas

#user_home
  #profile
    %h2 Que voudriez vous faire ?
    %ul
      %li= link_to "Voir votre profil", person_path(current_person)
      %li= link_to "Editer votre profil", edit_person_path(current_person)
      %li= link_to "Ajouter un ami à l'annuaire", new_person_path
      - if current_person.companies.blank?
        %li= link_to "Ajouter votre société", new_company_path
  #authentications
    %h2 Comptes liés
    = semantic_form_for(SignInData.new(:email => current_user.email), :url => user_sessions_path) do |f|
      = f.inputs do
        = f.input :email, :as => :hidden
        = f.input :provider, :collection => Authentication::PROVIDER_OPTIONS, :prompt => 'Choisissez un service…', :label => 'Ajoutez un compte'
      = f.buttons do
        = f.commit_button "Ajoutez le!"

    = render :partial => 'authentications/list', :object => current_user.authentications

app/views/users/index.html.haml
#users_admin
  %h1 Users
  %ul
    - @users.each do |user|
      %li{:id => "user_#{user.id}", :class => user.admin? ? 'admin' : nil}
        - if user.admin?
          %strong Admin
        = "User #{user.id}: #{user.name} -"
        = mail_to user.email
        = link_to "Supprimer", user_path(user), :confirm => 'Etes vous sûr?', :method => :delete, :class => 'delete'
        = link_to ((user.admin? ? 'Un-' : '') + 'adminify').capitalize, adminify_user_path(user), :method => :post, :class => 'make_admin'
        = image_tag(normalize_url(user.avatar_url), :size => '30x30', :align => 'right') if user.avatar_url
        %ul
          - if user.person.present?
            %li{:id => "person_#{user.person.id}"}
              = "Person #{user.person.id}:"
              = link_to user.person.name, person_path(user.person)
          - user.authentications.each do |auth|
            %li{:id => "authentication_#{auth.id}"}
              = "Authentication #{auth.id}: #{auth.info[:name]}"
              = "(#{auth.info[:nickname]})" if auth.info[:nickname]
              = "via #{provider_name(auth.provider)}"
              = link_to "Supprimer", authentication_path(auth), :confirm => 'Etes vous sûr ?', :method => :delete, :class => 'delete'
              - if auth.matching_person && auth.matching_person != user.person
                %ul
                  %li
                    = "Person #{user.id}:"
                    = link_to auth.matching_person.name, person_path(auth.matching_person)

app/views/users/welcome.html.haml
#welcome
  %h1= "Bonjour #{@name.split(' ').first}!"
  - if @possible_duplicates.present?
    #possible_duplicates
      %h2 Peut être que vous êtes cette personne ?
      %p.hint
        == Il semblerait que vous avez déjà été ajouté #{SETTINGS['organization']['name']}.
        = @possible_duplicates.size == 1 ? 'Est ce vous ?' : 'Etes vous l'une de ces personnes?'
      = render :partial => 'people/list', :object => @possible_duplicates, :locals => {:context => :claim}
  #add_yourself
    - if @person.new_record?
      %h2== Ajoutez vous à #{SETTINGS['organization']['name']}
      %p= "Nous avons importé autant d'information que possible de votre compte #{provider_name(current_user.authentications.first.provider)}. Tournez la tête et cliquez sur le gros bouton pour commencer."
    - else
      %h2 Vérifiez vos détails
      %p= "Vous êtes déjà dans la base de données ! Merci de vérifier vos détails et faites nous savoir s'ils sont bons."
    = render :partial => 'people/form', :locals => {:context => @person.new_record? ? :add_self : :review}