config/routes.rb
Citizenry::Application.routes.draw do 
  root :to => "site#index"

  get '/search(/:query)' => 'site#search', :as => :search
  get '/s(/:query)' => 'site#search', :as => :short_search
  get '/opensearch(.:format)' => 'site#opensearch', :as => :opensearch

  resources :authentications
  resources :companies do
    member do
      post 'join'
      post 'leave'
    end
  end
  get '/companies/tag/:tag(.:format)' => 'companies#tag', :as => 'companies_tagged', :constraints => {:tag => /.*/}

  resources :groups do
    member do
      post 'join'
      post 'leave'
    end
  end
  get '/groups/tag/:tag(.:format)' => 'groups#tag', :as => 'groups_tagged', :constraints => {:tag=> /.*/}

  resources :people do
    collection do
      get 'grid', :action => :index, :grid => '1'
    end
    member do
      get 'claim'
      get 'photo'
    end
  end
  get '/people/tag/:tag(.:format)' => 'people#tag', :as => 'people_tagged', :constraints => {:tag => /.*/}

  resources :projects do
    member do
      post 'join'
      post 'leave'
    end
  end
  get '/projects/tag/:tag(.:format)' => 'projects#tag', :as => 'projects_tagged', :constraints => {:tag => /.*/}

  resources :resources, :as => :resource_links, :controller => :resource_links

  resources :users, :only => [:show, :index, :destroy] do
    member do
      post 'adminify'
    end
  end
  get '/welcome' => 'users#welcome', :as => 'welcome_users'
  get '/home' => 'users#home', :as => 'home_users'

  resources :user_sessions, :only => [:new, :create], :controller => 'users/sessions'

  devise_for :users do
    get "/sign_out" => "devise/sessions#destroy"
    get "/sign_in" => "users/sessions#new"
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/auto' => 'authentications#auto'
  match '/auth/failure' => 'authentications#auth_failure'

  resources :changes, :controller => 'paper_trail_manager/changes'

end

app/models/project.rb
class Project < ActiveRecord::Base
  include SearchEngine
  has_paper_trail :ignore => [:delta]
  acts_as_taggable_on :tags, :technologies
  sortable :created_at, :desc

  has_attached_file :logo, :styles => { :medium => '220x220', :thumb => '48x48' }, :url => "/system/:attachment/:id/:style/:safe_filename"

  default_serialization_options :include => { :people => {:include => [:tags, :technologies]}, 
                                              :companies => {:include => [:tags, :technologies]},
                                              :groups  => {:include => [:tags, :technologies]},
                                              :tags => {},
                                              :technologies => {}}

  has_many :project_memberships
  has_many :people, :through => :project_memberships

  has_many :company_projects
  has_many :companies, :through => :company_projects

  has_many :group_projects
  has_many :groups, :through => :group_projects

  validates_presence_of :name
end




# == Schema Information
#
# Table name: projects
#
#  id                :integer(4)      not null, primary key
#  name              :string(255)
#  url               :string(255)
#  twitter           :string(255)
#  description       :text
#  created_at        :datetime
#  updated_at        :datetime
#  logo_file_name    :string(255)
#  logo_content_type :string(255)
#  logo_file_size    :integer(4)
#  logo_updated_at   :datetime
#  delta             :boolean(1)      default(TRUE), not null
#

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  respond_to :html, :xml, :json
  custom_actions  :collection => :tag,
                  :resource => [:join, :leave]

  before_filter :authenticate_user!, :except => [:index, :show, :tag]

  def tag
    @tag = params[:tag]
    @projects = Project.tagged_with(@tag)

    tag! do |format|
      format.html { render :action => :index }
    end
  end

  def show
    @project = Project.includes(:people).find(params[:id])
    show!
  end

  def join
    resource.people << current_person if current_person
    join!{ {:action => :show} }
  end

  def leave
    resource.people.delete(current_person) if current_person
    leave!{ {:action => :show} }
  end

  protected

  def collection
    @projects ||= filter_sort_and_paginate(end_of_association_chain)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= semantic_form_for(@project, :html => {:multipart => true}) do |f|
  = f.inputs do
    = f.input :name, :label => "Nom"
    = f.input :url, :label => 'Site web'
    = f.input :description
    = f.input :tag_list, :as => :text, :label => 'Tags', :hint => "Séparés par des virgules, svp", :input_html => {:class => 'tags'}
    = f.input :technology_list, :as => :text, :label => 'Technologies utilisées (langages, frameworks, etc)', :hint => "Séparés par des virgules, svp", :input_html => {:class => 'tags'}
    - if @project.logo.file?
      %li
        .faux_label Current logo
        = image_tag @project.logo.url(:medium) if @project.logo.present?
    = f.input :logo, :label => "Uploader un logo", :hint => "De préférence de 220px de large ou plus"
  = f.buttons

app/views/projects/_list.html.haml
- context ||= :general
%ul{:class => 'resource_list projects'}
  = render :partial => 'projects/list_item', :collection => list, :locals => {:context => context}
= render :partial => 'shared/list_pagination', :object => list

app/views/projects/_list_item.html.haml
- context ||= :general
%li.project
  - if list_item.logo.file?
    = link_to image_tag(list_item.logo.url(:thumb)), project_path(list_item), :class => 'avatar'
  %h3
    =link_to list_item.name, project_path(list_item)
  - if list_item.twitter.present?
    %span{:class => 'twitter_link'}
      %a{:href => "https://twitter.com/#{list_item.twitter}"}= "@#{list_item.twitter}"
      sur Twitter
  -#%p{:class=>'location'}= person['location']
  %p{:class=>'description'}= truncate(strip_links(list_item.description), :length => 350)

app/views/projects/edit.html.erb
<h1>Editer un projet</h1>

<%= render 'form' %>

<%= link_to 'Voir', @project %> |
<%= link_to 'Retour', projects_path %>

app/views/projects/index.html.haml
- content_for(:section_header) do
  .section_header{:class => 'projects'}
    %h1= semantic_pluralize(@projects.respond_to?(:total_entries) ? @projects.total_entries : @projects.size, "#{@tag} projet<span class='desktop-only'> ou produit</span>".strip.titleize.html_safe, "#{@tag} projets<span class='desktop-only'> & produits</span>".strip.titleize.html_safe)
    = link_to "+ Ajouter un projet", new_project_path, :class => 'new'
    #view_options
      %span.sorting
        %strong Trier par:
        = sort_link(:name, :label => "Nom") + ","
        = sort_link(:created_at, :label => "Date d'ajout", :default_order => :desc, :is_default => :desc) + ","
        = sort_link(:random, :label => "Aléatoire")

= render :partial => 'projects/list', :object => @projects

app/views/projects/new.html.erb
<h1>Nouveau projet</h1>

<%= render 'form' %>

<%= link_to 'Retour', projects_path %>

app/views/projects/show.html.haml
.single_record.project{:class => @project.logo.file? ? 'with_image' : 'without_image'}
  = image_tag(@project.logo.url(:medium), :class => 'logo') if @project.logo.file?
  %h1= @project.name
  - if @project.description.present?
    .description= simple_format @project.description
  .links
    - if @project.url.present?
      =link_to normalize_url(@project.url), normalize_url(@project.url), :class => 'url'

  .record_actions
    = link_to 'Editer', edit_project_path(@project), :class => 'edit'
    = link_to "Supprimer", project_path(@project), :confirm => 'Etes vous sûr?', :method => :delete, :class => 'delete'

  - if @project.tags.present?
    .section.tags
      %h2 Tags
      = render :partial => 'tags/list', :object => @project.tags, :locals => {:type => :project}

  - if @project.technologies.present?
    .section.technologies
      %h2 Technologies
      = render :partial => 'tags/list', :object => @project.technologies, :locals => {:type => :project}

  .section.members
    %h2 Membres
    - if current_person
      - if @project.people.include?(current_person)
        = link_to "Quitter ce projet", leave_project_path(@project), :class => 'leave', :method => :post
      - else
        = link_to "Rejoindre ce projet", join_project_path(@project), :class => 'join', :method => :post
    = render :partial => 'people/list', :object => @project.people, :locals => {:context => :member_list}