config/routes.rb
Citizenry::Application.routes.draw do 
  root :to => "site#index"

  get '/search(/:query)' => 'site#search', :as => :search
  get '/s(/:query)' => 'site#search', :as => :short_search
  get '/opensearch(.:format)' => 'site#opensearch', :as => :opensearch

  resources :authentications
  resources :companies do
    member do
      post 'join'
      post 'leave'
    end
  end
  get '/companies/tag/:tag(.:format)' => 'companies#tag', :as => 'companies_tagged', :constraints => {:tag => /.*/}

  resources :groups do
    member do
      post 'join'
      post 'leave'
    end
  end
  get '/groups/tag/:tag(.:format)' => 'groups#tag', :as => 'groups_tagged', :constraints => {:tag=> /.*/}

  resources :people do
    collection do
      get 'grid', :action => :index, :grid => '1'
    end
    member do
      get 'claim'
      get 'photo'
    end
  end
  get '/people/tag/:tag(.:format)' => 'people#tag', :as => 'people_tagged', :constraints => {:tag => /.*/}

  resources :projects do
    member do
      post 'join'
      post 'leave'
    end
  end
  get '/projects/tag/:tag(.:format)' => 'projects#tag', :as => 'projects_tagged', :constraints => {:tag => /.*/}

  resources :resources, :as => :resource_links, :controller => :resource_links

  resources :users, :only => [:show, :index, :destroy] do
    member do
      post 'adminify'
    end
  end
  get '/welcome' => 'users#welcome', :as => 'welcome_users'
  get '/home' => 'users#home', :as => 'home_users'

  resources :user_sessions, :only => [:new, :create], :controller => 'users/sessions'

  devise_for :users do
    get "/sign_out" => "devise/sessions#destroy"
    get "/sign_in" => "users/sessions#new"
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/auto' => 'authentications#auto'
  match '/auth/failure' => 'authentications#auth_failure'

  resources :changes, :controller => 'paper_trail_manager/changes'

end

app/models/company.rb
class Company < ActiveRecord::Base
  include SearchEngine
  has_paper_trail :ignore => [:delta]
  acts_as_taggable_on :tags, :technologies
  sortable :created_at, :desc

  has_attached_file :logo, :styles => { :medium => '220x220', :thumb => '48x48' }, :url => "/system/:attachment/:id/:style/:safe_filename"

  default_serialization_options :include => { :projects => {:include => [:tags, :technologies]}, 
                                              :groups => {:include => [:tags, :technologies]},
                                              :employees  => {:include => [:tags, :technologies]},
                                              :tags => {},
                                              :technologies => {}}

  has_many :company_projects
  has_many :projects, :through => :company_projects

  has_many :sponsorships
  has_many :groups, :through => :sponsorships

  has_many :employments
  has_many :employees, :through => :employments, :source => :person

  validates_presence_of :name
end




# == Schema Information
#
# Table name: companies
#
#  id                :integer(4)      not null, primary key
#  name              :string(255)
#  url               :string(255)
#  twitter           :string(255)
#  address           :text
#  description       :text
#  created_at        :datetime
#  updated_at        :datetime
#  logo_url          :string(255)
#  logo_file_name    :string(255)
#  logo_content_type :string(255)
#  logo_file_size    :integer(4)
#  logo_updated_at   :datetime
#  delta             :boolean(1)      default(TRUE), not null
#

app/controllers/companies_controller.rb
class CompaniesController < InheritedResources::Base
  respond_to :html, :xml, :json
  custom_actions  :collection => :tag,
                  :resource => [:join, :leave]

  before_filter :authenticate_user!, :except => [:index, :show, :tag]

  def tag
    @tag = params[:tag]

    tag! do |format|
      format.html { render :action => :index }
    end
  end

  def show
    @company = Company.includes(:employees).find(params[:id])
    show!
  end

  def join
    resource.employees << current_person if current_person
    join!{ {:action => :show} }
  end

  def leave
    resource.employees.delete(current_person) if current_person
    leave!{ {:action => :show} }
  end

  protected

  def collection
    @companies ||= filter_sort_and_paginate(end_of_association_chain)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.haml
= semantic_form_for(@company, :html => {:multipart => true}) do |f|
  = f.inputs do
    = f.input :name, :label => "Nom"
    = f.input :url, :label => 'Site web'
    = f.input :adresse, :as => :string, :hint => "e.g. 15 Av. Alsace Lorraine"
    = f.input :description
    = f.input :tag_list, :as => :text, :label => 'Tags (industries, sujets, etc)', :hint => "Séparés par des virgules, svp", :input_html => {:class => 'tags'}
    = f.input :technology_list, :as => :text, :label => 'Technologies utilisées (langages, frameworks, etc)', :hint => "Séparés par des virgules, svp", :input_html => {:class => 'tags'}
    - if @company.logo.file?
      %li
        .faux_label Current logo
        = image_tag @company.logo.url(:medium) if @company.logo.present?
    = f.input :logo, :label => "Uploader un logo", :hint => "De préférence de 220px de large ou plus"
  = f.buttons

app/views/companies/_list.html.haml
- context ||= :general
%ul{:class => 'resource_list companies'}
  = render :partial => 'companies/list_item', :collection => list, :locals => {:context => context}
= render :partial => 'shared/list_pagination', :object => list

app/views/companies/_list_item.html.haml
- context ||= :general
%li.company
  - if list_item.logo.file?
    = link_to image_tag(list_item.logo.url(:thumb)), company_path(list_item), :class => 'avatar'
  %h3
    =link_to list_item.name, company_path(list_item)
  - if list_item.twitter.present?
    %span{:class => 'twitter_link'}
      %a{:href => "https://twitter.com/#{list_item.twitter}"}= "@#{list_item.twitter}"
      sur Twitter
  -#%p{:class=>'location'}= person['location']
  %p{:class=>'description'}= truncate(strip_links(list_item.description), :length => 350)

app/views/companies/edit.html.erb
<h1>Editer la société</h1>

<%= render 'form' %>

<%= link_to 'Voir', @company %> |
<%= link_to 'Retour', companies_path %>

app/views/companies/index.html.haml
- content_for(:section_header) do
  .section_header{:class => 'companies'}
    %h1= semantic_pluralize(@companies.respond_to?(:total_entries) ? @companies.total_entries : @companies.size, "#{@tag} société".strip.titleize)
    = link_to "+ Ajouter une société", new_company_path, :class => 'new'
    #view_options
      %span.sorting
        %strong Trier par:
        = sort_link(:name, :label => "Nom") + ","
        = sort_link(:created_at, :label => "Date d'ajout", :default_order => :desc, :is_default => :desc) + ","
        = sort_link(:random, :label => "Aléatoire")

= render :partial => 'companies/list', :object => @companies

app/views/companies/new.html.erb
<h1>Nouvelle société</h1>

<%= render 'form' %>

<%= link_to 'Retour', companies_path %>

app/views/companies/show.html.haml
.single_record.company{:class => @company.logo.file? ? 'with_image' : 'without_image'}
  = image_tag(@company.logo.url(:medium), :class => 'logo') if @company.logo.file?
  %h1= @company.name
  - if @company.address.present?
    .location= @company.address
  - if @company.description.present?
    .description= simple_format @company.description
  .links
    - if @company.url.present?
      =link_to normalize_url(@company.url), normalize_url(@company.url), :class => 'url'

  .record_actions
    = link_to 'Editer', edit_company_path(@company), :class => 'edit'
    = link_to "Supprimer", company_path(@company), :confirm => 'Etes vous sûre?', :method => :delete, :class => 'delete'

  - if @company.tags.present?
    .section.tags
      %h2 Tags
      = render :partial => 'tags/list', :object => @company.tags, :locals => {:type => :company}

  - if @company.technologies.present?
    .section.technologies
      %h2 Technologies
      = render :partial => 'tags/list', :object => @company.technologies, :locals => {:type => :company}

  .section.members
    %h2 Employés
    - if current_person
      - if @company.employees.include?(current_person)
        = link_to "Quitter cette société", leave_company_path(@company), :class => 'leave', :method => :post
      - else
        = link_to "Rejoindre cette société", join_company_path(@company), :class => 'join', :method => :post
    = render :partial => 'people/list', :object => @company.employees, :locals => {:context => :member_list}